import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/components/common/Navbar";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <main>
          <div className="mx-72">
            <Navbar />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
